var I={zh:{"brand-sub":"热点日报","live-chip":"直播更新","hero-lbl":"▲ 今日最热","cat-top":"🔥 热门","cat-new":"💫 最新","cat-ask":"💬 问答","cat-show":"✨ 展示","cat-jobs":"💼 招聘","tf-top":"热门榜","tf-24h":"24小时","tf-week":"本周","refresh-txt":"刷新","footer-src":"数据来源：Hacker News API","last-upd":"最后更新","items":"条","fail":"加载失败，请检查网络后刷新"},en:{"brand-sub":"Daily News","live-chip":"LIVE","hero-lbl":"▲ TODAY'S TOP","cat-top":"🔥 Top","cat-new":"💫 New","cat-ask":"💬 Ask","cat-show":"✨ Show","cat-jobs":"💼 Jobs","tf-top":"Top","tf-24h":"24h","tf-week":"Week","refresh-txt":"Refresh","footer-src":"Powered by Hacker News API","last-upd":"Updated","items":" items","fail":"Failed to load. Check connection."}};
var LANG=localStorage.getItem("dp-lang")||"zh";
function t(k){return I[LANG][k]||I.zh[k]||k}
function setLang(l){LANG=l;localStorage.setItem("dp-lang",l);document.querySelectorAll(".lb").forEach(function(b){b.classList.toggle("active",b.dataset.lang===l)});var ids=["brand-sub","live-chip","hero-lbl","refresh-txt","footer-src","tf-top","tf-24h","tf-week"];ids.forEach(function(id){var el=document.getElementById(id);if(el)el.textContent=t(id)}});if(allByCat.technology&&allByCat.technology.length)renderAll();updateClock()}
function updateClock(){var n=new Date();document.getElementById("h-date").textContent=n.toLocaleDateString(LANG==="zh"?"zh-CN":"en-US",{weekday:"short",month:"short",day:"numeric"});document.getElementById("h-time").textContent=n.toLocaleTimeString(LANG==="zh"?"zh-CN":"en-US",{hour:"2-digit",minute:"2-digit"})+(LANG==="zh"?" CST":"")}
var LC={};
var GRAD={google:"#4285f4",openai:"#10a37f",github:"#24292e",microsoft:"#00a4ef",amazon:"#ff9900",apple:"#555",meta:"#0668e1",nvidia:"#76b900",tesla:"#e82127",spotify:"#1db954",netflix:"#e50914",twitter:"#1da1f2",reddit:"#ff4500",youtube:"#ff0000",ycombinator:"#ff6600",stripe:"#635bff",vercel:"#000",aws:"#ff9900",cloudflare:"#f38020",linear:"#5e6ad2",figma:"#f24e1e",notion:"#000",shopify:"#96bf48",tailwindcss:"#06b6d4",react:"#61dafb",typescript:"#3178c6",python:"#3776ab",mozilla:"#ff7139",archlinux:"#1793d1",debian:"#a80030",ubuntu:"#e95420",fedora:"#51a2da",golang:"#00add8",rust:"#ce422b",java:"#007396",stackoverflow:"#f48024",medium:"#00ab6c",techcrunch:"#0a9b4e",theverge:"#ec1c24",arstechnica:"#ff4e00",engadget:"#00bfff",mashable:"#45b8ac",bloomberg:"#000",nytimes:"#000",wsj:"#000",forbes:"#04040c",reuters:"#ff8000",bbc:"#bb1919",cnn:"#cc0000",ft:"#cc0000",economist:"#e3120b",hbr:"#c5203e"};
function getDomain(url){if(!url)return null;try{return new URL(url).hostname.replace("www.","")}catch(e){return null}}
function getLogo(domain){if(!domain)return null;if(!LC[domain])LC[domain]="https://logo.clearbit.com/https://"+domain;return LC[domain]}
function gradDU(domain,w,h){var c=document.getElementById("gc");c.width=w;c.height=h;var ctx=c.getContext("2d");var col=GRAD[domain]||"#1a1a2e";var g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,col+"18");g.addColorStop(1,col+"40");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle="rgba(255,255,255,.012)";for(var i=0;i<w;i+=20)for(var j=0;j<h;j+=20)if((i+j)%40===0)ctx.fillRect(i,j,8,8);return c.toDataURL()}
function logoImgLg(domain){var u=getLogo(domain);if(!u)return'<div class="hero-si-ph">📰</div>';return'<img class="hero-si-logo" src="'+u+'" alt="'+domain+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'" loading="lazy"><div class="hero-si-ph" style="display:none">📰</div>'}
function logoImgSm(domain){var u=getLogo(domain);if(!u)return'<div style="width:20px;height:20px;border-radius:4px;background:var(--bg2);border:1px solid var(--border);display:flex;align-items:center;justify-content:center;font-size:10px;flex-shrink:0">📰</div>';return'<img style="width:20px;height:20px;border-radius:4px;object-fit:contain;background:#fff;padding:2px;flex-shrink:0" src="'+u+'" alt="'+domain+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'" loading="lazy"><div style="width:20px;height:20px;border-radius:4px;background:var(--bg2);border:1px solid var(--border);display:none;align-items:center;justify-content:center;font-size:10px;flex-shrink:0">📰</div>'}
function logoImgXs(domain){var u=getLogo(domain);if(!u)return'<div style="width:28px;height:28px;border-radius:6px;background:var(--bg2);border:1px solid var(--border);display:flex;align-items:center;justify-content:center;font-size:12px">📰</div>';return'<img style="width:28px;height:28px;border-radius:6px;object-fit:contain;background:#fff;padding:3px" src="'+u+'" alt="'+domain+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'" loading="lazy"><div style="width:28px;height:28px;border-radius:6px;background:var(--bg2);border:1px solid var(--border);display:none;align-items:center;justify-content:center;font-size:12px">📰</div>'}
function num(n){return n>=1000?(n/1000).toFixed(1)+"k":n}
function timeAgo(ts){if(!ts)return"";var d=Date.now()/1000-(new Date(ts).getTime()/1000);if(d<60)return Math.floor(d)+"s";if(d<3600)return Math.floor(d/60)+"m";if(d<86400)return Math.floor(d/3600)+"h";return Math.floor(d/86400)+"d"}
function getStoryId(s){return s.objectID||s.id}
function getStoryTitle(s){return s.title||""}
function getStoryUrl(s){return s.url||("https://news.ycombinator.com/item?id="+(s.objectID||s.id))}
function getStoryScore(s){return s.points||s.score||0}
function getStoryAuthor(s){return s.author||s.by||""}
function getStoryComments(s){return s.num_comments||s.descendants||0}
function getStoryTime(s){return s.created_at?s.created_at:(s.time?new Date(s.time*1000).toISOString():"")}
var HN="https://hn.algolia.com/api/v1";
var CAT_DEF=[{id:"top",key:"top",icon:"🔥",label:"热门",tag:"story"},{id:"new",key:"newest",icon:"💫",label:"最新",tag:"story"},{id:"ask",key:"ask",icon:"💬",label:"问答",tag:"ask_hn"},{id:"show",key:"show",icon:"✨",label:"展示",tag:"show_hn"},{id:"jobs",key:"jobs",icon:"💼",label:"招聘",tag:"job"}];
var allByCat={},timeFilter="top",storiesShown={};
async function fetcher(url){return fetch(url).then(function(r){return r.json()}).catch(function(){return null})}
async function loadAll(){var btn=document.getElementById("refresh-btn");btn.disabled=true;showSkeleton();try{var r=await Promise.all(CAT_DEF.map(function(c){var tag=c.tag;var url=HN+"/search?tags="+tag+"&hitsPerPage=30";return fetcher(url).then(function(d){return(d&&d.hits)||[]})},function(e){return[]}));allByCat={top:r[0],technology:r[0],newest:r[1],ask_hn:r[2],show_hn:r[3],jobs:r[4]};storiesShown={};CAT_DEF.forEach(function(c){storiesShown[c.id]=filtered(c.key)});renderAll();document.getElementById("last-upd").textContent=t("last-upd")+": "+new Date().toLocaleTimeString(LANG==="zh"?"zh-CN":"en-US")}catch(e){console.error(e)}btn.disabled=false}
function cutoff(){var now=Date.now()/1000;return timeFilter==="24h"?now-86400:timeFilter==="week"?now-604800:0}
function filtered(key){var c=cutoff();return(allByCat[key]||[]).filter(function(s){return!s.time||s.time>=c})}
function showSkeleton(){document.getElementById("hero-main").innerHTML='<div class="sk" style="width:100%;height:100%;border-radius:var(--r18)"></div>';document.getElementById("hero-side").innerHTML=Array(4).fill().map(function(){return'<div class="sk" style="height:78px;border-radius:var(--r14)"></div>'}).join("");document.getElementById("category-strips").innerHTML=CAT_DEF.map(function(c){return'<div class="cat-row" id="cat-row-'+c.id+'"><div class="cat-row-hdr"><div class="cat-row-title" style="color:var(--txt3)">'+c.icon+" "+c.label+'</div></div><div class="cat-grid">'+Array(4).fill().map(function(){return'<div class="sk" style="height:220px"></div>'}).join("")+"</div></div>"}).join("")}
function renderAll(){CAT_DEF.forEach(function(c){storiesShown[c.id]=filtered(c.key)});renderHero();renderTabs();renderStrips()}
function renderHero(){var all=storiesShown.top||[];var main=all[0],sides=all.slice(1,5);var hm=document.getElementById("hero-main");if(!main){hm.innerHTML='<p style="color:var(--txt2);padding:40px">'+t("fail")+"</p>";return}var domain=getDomain(getStoryUrl(main));var bg=gradDU(domain,900,400);var mainUrl=getStoryUrl(main);hm.innerHTML='<div class="hero-bg" style="background:url('+bg+') center/cover"></div><div class="hero-c"><div class="hero-num">#1</div><div class="hero-src"><div class="hero-chip">'+logoImgSm(domain)+'<span class="hero-chip-nm">'+(domain||"news.ycombinator.com")+'</span></div><div class="hero-badge">🔥 热门</div></div><div class="hero-title">'+getStoryTitle(main)+'</div><div class="hero-meta"><span class="hero-score">▲ '+num(getStoryScore(main))+'</span><span class="hero-comments">💬 '+num(getStoryComments(main))+'</span><span class="hero-author">👤 '+getStoryAuthor(main)+'</span><span>⏱ '+timeAgo(getStoryTime(main))+"</span></div></div>";hm.style.cursor="pointer";hm.setAttribute("data-url",mainUrl);hm.onclick=function(){window.open(this.getAttribute("data-url"),"_blank")};document.getElementById("hero-side").innerHTML=sides.map(function(s,i){var d=getDomain(getStoryUrl(s));var url=getStoryUrl(s);return'<div class="hero-si" data-url="'+url.replace(/"/g,"&quot;")+'"><div class="hero-si-num">#'+(i+2)+"</div>"+logoImgLg(d)+'<div class="hero-si-info"><div class="hero-si-title">'+getStoryTitle(s)+'</div><div class="hero-si-meta"><span class="hero-si-score">▲ '+num(getStoryScore(s))+'</span><span class="hero-si-cmts">💬 '+num(getStoryComments(s))+'</span><span>⏱ '+timeAgo(getStoryTime(s))+"</span></div></div></div>"}).join("");document.querySelectorAll(".hero-si").forEach(function(el){el.onclick=function(){window.open(this.getAttribute("data-url"),"_blank")}})}}
function renderTabs(){var tabs=document.getElementById("cat-tabs");tabs.innerHTML=CAT_DEF.map(function(c){return'<button class="cat-tab'+(c.id==="top"?" active":"")+'" data-cat="'+c.id+'">'+c.icon+' <span>'+c.label+'</span> <span style="font-size:10px;color:var(--txt3);font-family:\'JetBrains Mono\',monospace">('+Math.min((storiesShown[c.id]||[]).length,20)+")</span></button>"}).join("");tabs.querySelectorAll(".cat-tab").forEach(function(btn){btn.onclick=function(){tabs.querySelectorAll(".cat-tab").forEach(function(b){b.classList.remove("active")});btn.classList.add("active");var catId=btn.dataset.cat;var row=document.getElementById("cat-row-"+catId);if(row)row.scrollIntoView({behavior:"smooth",block:"start"})}})}
function renderStrips(){CAT_DEF.forEach(function(c){var row=document.getElementById("cat-row-"+c.id);if(!row){row=document.createElement("div");row.className="cat-row";row.id="cat-row-"+c.id;document.getElementById("category-strips").appendChild(row)}var stories=storiesShown[c.id]||[];row.innerHTML='<div class="cat-row-hdr"><div class="cat-row-title">'+c.icon+" <span>"+c.label+'</span><span class="cat-row-count">'+stories.length+t("items")+'</span></div></div><div class="cat-grid">'+stories.slice(0,8).map(function(s,i){var d=getDomain(getStoryUrl(s));var bg=gradDU(d,400,120);var url=getStoryUrl(s);return'<div class="strip-card" style="animation-delay:'+(i*0.06)+'s" data-url="'+url.replace(/"/g,"&quot;")+'"><div class="strip-img"><div class="strip-bg" style="background:url('+bg+') center/cover"></div><div class="strip-logo">'+logoImgXs(d)+"</div></div><div class=\"strip-body\"><div class=\"strip-source\">"+(d||"news.ycombinator.com")+'</div><div class="strip-title">'+getStoryTitle(s)+'</div><div class="strip-footer"><span class="strip-author">👤 '+getStoryAuthor(s)+'</span><div class="strip-stats"><span class="strip-score">▲ '+num(getStoryScore(s))+'</span><span class="strip-cmts">💬 '+num(getStoryComments(s))+"</span></div></div></div></div>"}).join("")+"</div>"});document.querySelectorAll(".strip-card").forEach(function(el){el.onclick=function(){window.open(this.getAttribute("data-url"),"_blank")}})}}
document.querySelectorAll(".lb").forEach(function(b){b.onclick=function(){setLang(b.dataset.lang)}});
document.querySelectorAll(".tb").forEach(function(btn){btn.onclick=function(){document.querySelectorAll(".tb").forEach(function(b){b.classList.remove("active")});btn.classList.add("active");timeFilter=btn.dataset.time;if(Object.keys(storiesShown).length)renderAll()}});
